name: 'Main'

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  checks:
    uses: nzbr/actions/.github/workflows/run_checks.yml@main
    secrets:
      SECRET_DECRYPTION_KEY: ${{ secrets.SECRET_DECRYPTION_KEY }}
